# Generated by Django 4.1.7 on 2023-02-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermodel',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
