# Generated by Django 4.1.7 on 2023-02-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermodel',
            options={'verbose_name_plural': 'Customers'},
        ),
    ]
